name: '[Reusable] Update release Pull Request'
on:
  workflow_call:
jobs:
  calc_version:
    uses: ./.github/workflows/calc_version.yml
  get_pr_list:
    uses: ./.github/workflows/_internal_get_pr_list.yml
  update_release_pr_comment:
    needs: [calc_version, get_pr_list]
    uses: ./.github/workflows/_internal_create_or_update_pr_comment.yml
    with:
      body: |
        This Pull Request is for a release. If you approve it, a release will be created.

        **Please do not add any tags other than \`Release\`.**  
        Adding other tags may result in an unintended release or incorrect version.

        Version: \`${{ needs.calc_version.outputs.current_version }}\` â†’ \`${{ needs.calc_version.outputs.version }}\`  

        ${{ needs.get_pr_list.outputs.pr_list }}
